# Generated by Django 4.1.2 on 2022-10-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variatoin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variatoin',
            new_name='Variation',
        ),
    ]
