# Generated by Django 4.1.2 on 2022-10-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_variatoin_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variarion_category',
            new_name='variation_category',
        ),
    ]
